apiVersion: v1
kind: Service
metadata:
  name: ollama-runtime
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "ollama-runtime.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "ollama-runtime.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: ollama
      port: {{ .Values.ollama.servicePort }}
      targetPort: ollama
    - name: agent
      port: {{ .Values.agent.servicePort }}
      targetPort: agent
