apiVersion: v1
kind: Service
metadata:
  name: {{ include "obc.name" . }}-agent
  labels:
    {{- include "obc.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.agent.service.port }}
      targetPort: 9000
