apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  labels:
    {{- include "obc.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: ollama
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ollama
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          ports:
            - containerPort: 11434
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
          readinessProbe:
            httpGet:
              path: /api/version
              port: 11434
          livenessProbe:
            httpGet:
              path: /api/version
              port: 11434
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: {{ include "obc.name" . }}-ollama
