apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "obc.name" . }}-ollama
  labels:
    {{- include "obc.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
