apiVersion: v1
kind: Secret
metadata:
  name: {{ include "obc.name" . }}-secret
  labels:
    {{- include "obc.labels" . | nindent 4 }}
type: Opaque
stringData:
  BACKEND_API_KEY: {{ .Values.backend.apiKey | quote }}
  BENCH_AGENT_API_KEY: {{ .Values.agent.apiKey | quote }}
  {{- if not .Values.backend.database.urlFromSecret }}
  BACKEND_DATABASE_URL: {{ .Values.backend.database.url | quote }}
  {{- end }}
