apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "obc.name" . }}
  labels:
    {{- include "obc.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "obc.name" . }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "obc.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "obc.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "obc.name" . }}
