namespace:
  create: true
  name: ollama

ollama:
  image: ollama/ollama
  tag: 0.30.8
  pullPolicy: Always
  servicePort: 11434
  resources:
    limits:
      nvidia.com/gpu: 1

agent:
  image: ghcr.io/joshiparth1000/ollama-benchmark-center/agent
  tag: "cb34ecf"
  pullPolicy: Always
  servicePort: 9000
  apiKey: dev-agent-key
  gpuAccess:
    enabled: true
    privileged: true
    hostBinPath: /usr/bin
    hostLibFile: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
    hostDevPath: /dev

persistence:
  hostPath: /data/ollama

nodeSelector:
  accelerator: nvidia

tolerations:
  - key: nvidia.com/gpu
    operator: Equal
    value: "true"
    effect: NoSchedule

service:
  type: NodePort
