namespace:
  create: true
  name: ollama

ollama:
  image: ollama/ollama
  tag: 0.30.8
  pullPolicy: Always
  servicePort: 11434

agent:
  image: ghcr.io/joshiparth1000/ollama-benchmark-center/agent
  tag: a6da635
  pullPolicy: Always
  servicePort: 9000
  apiKey: dev-agent-key

persistence:
  hostPath: /data/ollama

nodeSelector:
  accelerator: nvidia

tolerations:
  - key: nvidia.com/gpu
    operator: Equal
    value: "true"
    effect: NoSchedule

service:
  type: NodePort
